name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}
      run: |
        echo $USER
        echo $PASS
        docker build /home/runner/work/DCM_3008/DCM_3008/ --file Dockerfile --tag akhid4/dcm_webserver
        docker login -u $USER -p $PASS
        docker push akhid4/dcm_webserver
